apiVersion: v1
kind: Service
metadata:
  name: users
  labels:
    app: users
spec:
  ports:
    - name: http
      port: 8080
  selector:
    app: users
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: users
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: users
        version: v1
    spec:
      containers:
        - image: users:v1
          imagePullPolicy: Never
          name: users
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_HOST
              value: 192.168.65.2