apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  labels:
    app: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: server:v3
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_HOST
              value: mongo
          readinessProbe:
            timeoutSeconds: 1
            periodSeconds: 1
            failureThreshold: 5
            initialDelaySeconds: 10
            httpGet:
              port: 8080
              path: /
          livenessProbe:
            timeoutSeconds: 1
            periodSeconds: 1
            failureThreshold: 5
            initialDelaySeconds: 10
            httpGet:
              port: 8080
              path: /
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

---

apiVersion: v1
kind: Service
metadata:
  name: server-service
  labels:
    app: server
spec:
  selector:
    app: server
  type: LoadBalancer
  ports:
    - port: 8080

---

kind: Service
apiVersion: v1
metadata:
  name: mongo
spec:
  type: ExternalName
  externalName: host.docker.internal
