---
apiVersion: v1
kind: Service
metadata:
  name: users-service
  labels:
    app: users
spec:
  selector:
    app: users
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: http
---

kind: Service
apiVersion: v1
metadata:
  name: mongo-host
spec:
  type: ExternalName
  externalName: host.docker.internal
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
  labels:
    app: users
  annotations:
    flux.weave.works/automated: 'true'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
      - name: users
        image: localhost:5000/users:DEV
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: MONGO_HOST
          value: mongo-host
        readinessProbe:
          timeoutSeconds: 10
          periodSeconds: 10
          failureThreshold: 5
          initialDelaySeconds: 20
          httpGet:
            port: http
            path: /actuator/health
        livenessProbe:
          timeoutSeconds: 10
          periodSeconds: 10
          failureThreshold: 5
          initialDelaySeconds: 20
          httpGet:
            port: http
            path: /actuator/health
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
